### ISSUE TITLE
Problems with play-services-ads version

### ISSUE THREAD

**Issue by sverdlov** [BranchMetrics/capacitor-branch-deep-links#111]
### Describe the bug

Not long time ago Google Play started to show message about play-services-ads and play-services-ads-lite versions sunset 
`This version is scheduled to sunset on June 30th 2023. See https://developers.google.com/admob/android/deprecation for more information.`
In [documentation](https://help.branch.io/developers-hub/docs/capacitor#android) version 19.4.0 is specified.
I've tried update it to latest but app is crashing with error
```
******************
* The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
* should follow the instructions here:                                       *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to add a valid App ID inside the AndroidManifest.                          *
* Google Ad Manager publishers should follow instructions here:              *
* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
******************
```
I see that I have to add AdMob app ID, but I'm not sure what it is, where I shoult get it and does it requred at all.

### Steps to reproduce

1. Update com.google.android.gms:play-services-ads:19.4.0 to the latest version

### Expected behavior

-

### SDK Version

5.0.0

### Make and Model

Xiaomi 10T Pro

### OS

Android

**Comment by avisiboni** [comment]
Same issue here, any update?

**Comment by gdeluna-branch** [comment]
We'll bump the version publish an update soon.

**Comment by gdeluna-branch** [comment]
I tested with `implementation("com.google.android.gms:play-services-ads-identifier:18.0.1")` and it succeeded.
@avisiboni @sverdlov can you confirm if that version works for you? We'll update the docs to reflect if so. 

It'll be a code change otherwise to get the latest supported.

**Comment by sverdlov** [comment]
@gdeluna-branch that's strange because it's also should be deprecated [https://developers.google.com/admob/android/deprecation](as specified in docs). I think version should be upgraged not downgraded. And at least for 21, because 20 is already deprecated

**Comment by gdeluna-branch** [comment]
Thanks for pointing out the timeline. Unsure why my environment shows no warning. I'll post back when we've made the changes.

**Comment by gdeluna-branch** [comment]
I think there was some confusion as to which library is getting deprecated. 

Our native android sdk [documentation](https://help.branch.io/developers-hub/docs/android-basic-integration#dependencies) correctly suggests 
`implementation "com.google.android.gms:play-services-ads-identifier:18.0.1"`

However our [capacitor sdk doc](https://help.branch.io/developers-hub/docs/capacitor#android) incorrectly says
`implementation 'com.google.android.gms:play-services-ads:19.4.0' // GAID matching`


The library we require for GAID is 
https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads-identifier?repo=google

The latest being [18.0.1](https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads-identifier/18.0.1).

Warning with `ads:19.4.0`
<img width="1507" alt="image" src="https://github.com/BranchMetrics/capacitor-branch-deep-links/assets/94577415/76850eca-ad2d-4efd-8d5b-aa0c2bee7a22">



No warning with `ads-identifier:18.0.1`
<img width="678" alt="image" src="https://github.com/BranchMetrics/capacitor-branch-deep-links/assets/94577415/8f1a1404-5f74-4825-b3a3-498619169310">

Please let me know if importing `com.google.android.gms:play-services-ads-identifier:18.0.1` works for you.

**Comment by sverdlov** [comment]
@gdeluna-branch yes, you are right, I confused libs. Seems like with `com.google.android.gms:play-services-ads-identifier:18.0.1` all works great. Thank you.
