### ISSUE TITLE
Can't generate deep link Error: BranchDeepLinks does not have web implementation

### ISSUE THREAD

**Issue by arianshirepublik** [BranchMetrics/capacitor-branch-deep-links#116]
### Describe the bug

Hi When I used "capacitor-branch-deep-links": "5.0.0" in Web.
It is sitll show errors:
<img width="778" alt="image" src="https://github.com/BranchMetrics/capacitor-branch-deep-links/assets/133647949/22f8d80e-8efe-4664-8501-a6a582918a11">

Is there an updated answer to this question?

Steps to reproduce

I used "capacitor-branch-deep-links": "5.0.0",
It is sitll show errors:
<img width="778" alt="image" src="https://github.com/BranchMetrics/capacitor-branch-deep-links/assets/133647949/22f8d80e-8efe-4664-8501-a6a582918a11">

Expected behavior

 Generated right deep link 

SDK Version

5.0.0

Make and Model

chrome

OS

chrome

**Comment by gdeluna-branch** [comment]
We currently don't support a capacitor web implementation.
