### ISSUE TITLE
Capacitor BranchDeepLinks.addListener is not working as a listener

### ISSUE THREAD

**Issue by GiannisS** [BranchMetrics/capacitor-branch-deep-links#127]
### Describe the bug

The addListener function is not working as a listener meaning that if new refferingParams arrive to App you will have to call again the BranchDeepLinks.addListener function in order to read them.

### Steps to reproduce

Just initialize 
``` 
        BranchDeepLinks.addListener("init", (event: BranchInitEvent) => {
          console.log("Deep Link branch Data:", event.referringParams);
        });
```

With your app opened and initialized just try Browser.open({url: "your branch url"}). The listener will never detect the new data.

### Expected behavior

The addListener function should detect new data without the need of calling the function everytime you know new data will arrive. Otherwise the function (addListener) is missnamed and missleading.

### SDK Version

7.0.0

### Make and Model

Any android

### OS

Android 13

**Comment by marshall86** [comment]
what's the status of this bug? Any updates?

**Comment by metinjakupi** [comment]
Bump

**Comment by metinjakupi** [comment]
@GiannisS did you find a solution?

**Comment by GiannisS** [comment]
issue is still there
