### ISSUE TITLE
Type 'Branch' has no member 'setDMAParamsForEEA'

### ISSUE THREAD

**Issue by GiannisS** [BranchMetrics/capacitor-branch-deep-links#147]
### Describe the bug

On iOS after the last update about setDMAParamsForEEA when I try to build my app in xCode I get this following error

Type 'Branch' has no member 'setDMAParamsForEEA'

### Steps to reproduce

1.Try to build any app using the latest version of capacitor-branch-deep-links

### Expected behavior

No errors

### SDK Version

7.1.0

### Make and Model

Simulator iPhone 15 Pro 

### OS

17.2

**Comment by nsingh-branch** [comment]
You may need to run `pod install` in your project's iOS folder to make sure the proper Branch iOS SDK version is being pulled as well.

**Comment by GiannisS** [comment]
This didn't seem to help! I still get the same error here
![image](https://github.com/BranchMetrics/capacitor-branch-deep-links/assets/32912583/190b4638-68b9-4bfb-b194-91c3e2720032)

it seems that the required functions do exist though in plugin.swift file.

**Comment by sufyankhatri** [comment]
found the same issue

**Comment by raghudantuluri** [comment]
we are experiencing the same issue

**Comment by nsingh-branch** [comment]
@GiannisS If you navigate to the iOS folder of your project and open the Podfile.lock, what versions do you see for BranchSDK and CapacitorBranchDeepLinks?

**Comment by raghudantuluri** [comment]
I am able to run pod update and get the latest branch sdk and included that
in the build, and now our podlock file looks like this.

PODS:

  - BranchSDK (3.4.3)

  - Capacitor (5.7.2):

    - CapacitorCordova

  - CapacitorApp (5.0.7):

    - Capacitor

  - CapacitorBranchDeepLinks (7.1.0):

    - BranchSDK

    - Capacitor



And these are the logs I see related to branch from Xcode, still not
getting referringparams after install



[BranchSDK][Debug][Branch
initializeSessionAndCallCallback:sceneIdentifier:urlString:] Request
<BranchInstallRequest: 0x303d0a7a0> callback <__NSMallocBlock__:
0x302c5d4c0> link (null)

[BranchSDK][Debug][BNCServerInterface
preparePostRequest:url:key:retryNumber:] <NSMutableURLRequest: 0x303b18310>
{ URL: https://api3.branch.io/v1/install }

Headers {

    "Content-Length" = 1688;

    "Content-Type" = "application/json";

}

Body {

  "anon_id" : "719_________________A41",

  "app_version" : "__._.__",

  "apple_attribution_token" : "______",

  "apple_testflight" : true,

  "branch_key" : "key_live________",

  "brand" : "Apple",

  "build" : "___",

  "connection_type" : "wifi",

  "country" : "US",

  "cpu_type" : "16777228",

  "debug" : false,

  "environment" : "FULL_APP",

  "first_install_time" : 1703564954000,

  "hardware_id" : "___",

  "hardware_id_type" : "vendor_id",

  "ios_bundle_id" : "______",

  "ios_vendor_id" : "_____",

  "is_hardware_id_real" : true,

  "language" : "en",

  "lastest_update_time" : 1714138566000,

  "latest_install_time" : 1714138568219,

  "local_ip" : "____",

  "locale" : "en_US",

  "metadata" : {

    "skan_time_window" : "5184000.000000"

  },

  "model" : "___",

  "opted_in_status" : "denied",

  "os" : "iOS",

  "os_version" : "17.4.1",

  "plugin_name" : "Capacitor",

  "plugin_version" : "7.0.0",

  "retryNumber" : 0,

  "screen_dpi" : 3,

  "screen_height" : 2556,

  "screen_width" : 1179,

  "sdk" : "ios3.4.3",

  "update" : 0,

  "uri_scheme" : "____",

  "user_agent" : "Mozilla\/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X)
AppleWebKit\/605.1.15 (KHTML, like Gecko) Mobile\/15E148"

}

Failed to request allowed query parameters from WebPrivacy.



⚡️  To Native ->  BranchDeepLinks addListener 98742127

⚡️  To Native ->  BranchDeepLinks addListener 98742128

[BranchSDK][Debug][BNCServerInterface processServerResponse:data:error:]
<NSHTTPURLResponse: 0x303937100> { URL: https://api3.branch.io/v1/install }
{ Status Code: 200, Headers {

    "Access-Control-Allow-Origin" =     (

        "*"

    );

    "Content-Length" =     (

        283

    );

    "Content-Type" =     (

        "application/json; charset=utf-8"

    );

    Date =     (

        "Fri, 26 Apr 2024 13:36:17 GMT"

    );

    "Strict-Transport-Security" =     (

        "max-age=31536000; includeSubDomains"

    );

    Via =     (

        "1.1 a147f9c60c162e36df3586fdd9c01478.cloudfront.net (CloudFront)"

    );

    "x-amz-cf-id" =     (

        "gz-____=="

    );

    "x-amz-cf-pop" =     (

        "PHL51-P1"

    );

    "x-branch-request-id" =     (

        "_____"

    );

    "x-cache" =     (

        "Miss from cloudfront"

    );

    "x-powered-by" =     (

        Branch

    );

} }

Body {

  "data" : "{\"+clicked_branch_link\":false,\"+is_first_session\":true}",

  "link" : "https:\/\/_____.app.link?%24randomized_bundle_token=____",

  "randomized_bundle_token" : "___",

  "randomized_device_token" : "___",

  "session_id" : "1312399193406720942"

}

Branch initSession, got params - :

["+clicked_branch_link": 0, "+is_first_session": 1]

⚡️  [log] -  APP COMP - initExternalLinks - BranchDeepLinks init got
event:  {"referringParams":{}}

**Comment by nsingh-branch** [comment]
I see, so the issue was the Branch iOS SDK version was out of date. But running `pod update` was able to fix this.

**Comment by raghudantuluri** [comment]
Fixed the error but still not working. Referring params are coming empty
for deferred deep links.
