### ISSUE TITLE
Clarify Documentation

### ISSUE THREAD

**Issue by selected-pixel-jameson** [BranchMetrics/capacitor-branch-deep-links#20]
Can you please clarify this statement in the Android setup documentation.

```
Declare BranchApp as your application class in src/main/AndroidManifest.xml:

  <application
+     android:name="io.branch.referral.BranchApp"
```

Is android:name supposed too explicitly be "io.branch.referral.BranchApp" or is it supposed to be the name of your specific app? When I enter this in my AndroidManfest.xml file it tells me that it doesn't exist. However, the deep links still work and the app compiles.

**Comment by selected-pixel-jameson** [comment]
Any immediate help with this would be much appreciated. My app is reporting 1000's of crashes daily and I need to figure out what is causing this as I can't replicate it on the emulator or actual devices.

**Comment by tafelnl** [comment]
@selected-pixel-jameson 

This answer can probably help you out: https://github.com/BranchMetrics/capacitor-branch-deep-links/issues/21#issuecomment-703516155
