### ISSUE TITLE
Android > App Crash > Additional functions

### ISSUE THREAD

**Issue by KirstenStake** [BranchMetrics/capacitor-branch-deep-links#31]
When using plugin v3.0.0 my app crashes on Android with no error messages when calling functions:
- BranchDeepLinks.generateShortUrl()
- BranchDeepLinks.showShareSheet()

I haven't tried some other functions other than those two, so some of the others might crash the app too.

When downgrading to v2.0.0 there are no issues and everything works as expected.

Additional environment information:
- Ionic 5
- Capacitor
- Angular 11

**Comment by selected-pixel-jameson** [comment]
Sounds about right. I don't know that I've ever seen an actual response from their team members in this repo.

**Comment by tafelnl** [comment]
I am not on the branch team. So unfortunately I cant help. I could try to claim ownership of this repo though and transfer it to the capacitor community.

Though, I do not have very much time on my hands, so if anyone would like to volunteer for this, that would be awesome

**Comment by KirstenStake** [comment]
PR was merged in. closing issue thanks.
