### ISSUE TITLE
Capacitor 3.0 Support 

### ISSUE THREAD

**Issue by KirstenStake** [BranchMetrics/capacitor-branch-deep-links#34]
Please update the plugin to support Capacitor 3.0 ([https://capacitorjs.com/docs/v3/updating/plugins/3-0](https://capacitorjs.com/docs/v3/updating/plugins/3-0))

Have updated my project and am getting errors with this package, especially when importing the plugin into the files now as they are no longer supported via the @capacitor/core plugin import.

**Comment by stevecarlton** [comment]
+1. @KirstenStake I reached out to support so they can look and see why the plugin seems neglected. I'll let you know if I hear anything back.

**Comment by KirstenStake** [comment]
@stevecarlton have contacted them twice now as well and each time they say will forward on to dev team followed by nothing happening. will follow up again today.

**Comment by vitorlopez** [comment]
I can see there's an already merged PR https://github.com/BranchMetrics/capacitor-branch-deep-links/pull/37 but it seems this didn't get to master yet. When can we expect for that to happen?

**Comment by paulstelzer** [comment]
If you cannot wait like me, I have forked this project to support capacitor 3 -> https://github.com/paulstelzer/capacitor-branch-deep-links

I am already using it inside a production app and it's working :) Hopefully the branch team will update to capactor 3 soon, so I can delete my fork.

**Comment by vitorlopez** [comment]
That's amazing. Thanks for that fork.

**Comment by stevecarlton** [comment]
Thank you Paul!

**Comment by gabides** [comment]
@echo-branch thanks for merging my PR for capacitor 3 support, any timeline on when this will be on master and/or when a version will be released on npm for cap 3?

**Comment by KirstenStake** [comment]
@echo-branch please provide an update on what you will be able to merge the changes in staging to master for Cap 3 support?

**Comment by selected-pixel-jameson** [comment]
@echo-branch Please update this repo! It's getting to the point where we are being forced to updated to Capacitor 3 for other plugins so we have no choice. This is preventing us from releasing new app versions.

**Comment by KirstenStake** [comment]
@selected-pixel-jameson i emailed branch a week or so ago with the same question, they advised me that the branch has been merged in (can confirm it has) and it supports Capacitor 3. They forgot to update the CHANGELOG hence where I think our confusion lies.

To update the iOS SDK follow the following steps:
- a clean and rebuild should refresh to the latest SDK automatically since it's a patch release.
- delete the cocoapods lock file and Pods folder.
- do a pod update

Now to enable the features in that SDK, follow the instructions on the docs site. 
https://help.branch.io/developers-hub/docs/capacitor#nativelink-deferred-deep-linking-ios-only

Did the above steps last week and am now on the latest. let me know how you go.

**Comment by selected-pixel-jameson** [comment]
@kristenstake

Did this fix the iOS deployment target of 11 being set?

Jameson W Parker

**Comment by selected-pixel-jameson** [comment]
@echo-branch What @KirstenStake suggested did not fix the issue. I'm still getting a build error stating that the CapacitoBranchDeepLinks project is compiling for iOS 11.0

If you look on the master branch or version 4.0.0 it's very clear to see that this project is still set to use iOS 11.0 as a deployment target, which is what is causing the issue. If I change the deployment target manually in my XCode project it builds fine, however every time I do a new build this gets reset which is a non-starter. 

This is from the Pod file [https://github.com/BranchMetrics/capacitor-branch-deep-links/blob/master/ios/Podfile]
```
platform :ios, '11.0'

def capacitor_pods
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'Branch', '~> 1.39.2'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end
```

This is from the iOS project File [https://github.com/BranchMetrics/capacitor-branch-deep-links/blob/master/ios/Plugin.xcodeproj/project.pbxproj]
```
IPHONEOS_DEPLOYMENT_TARGET = 11.0;
```

**Comment by selected-pixel-jameson** [comment]
@echo-branch Furthermore it looks like there is a pull request out there that is doing almost all of this for you. It looks like it just needs the Deployment Target set correctly. https://github.com/BranchMetrics/capacitor-branch-deep-links/pull/46

**Comment by selected-pixel-jameson** [comment]
@echo-branch This is the only capacitor plug-in that is preventing us from moving forward. Please accept pull request #46 and release a new version.

**Comment by selected-pixel-jameson** [comment]
@paulstelzer Thanks for posting a version of this repo that actually builds for capacitor 3. For all other who are stuck where I have been install this NPM package https://www.npmjs.com/package/@innomobile/capacitor-branch-deep-links.

**Comment by KirstenStake** [comment]
Further to selected-pixel-jameson's comments. manually updating target to 12, passes build for me but causes a whole bunch of deprecation errors (when doing automated build it breaks as it doesn't pass these deprecation errors as well as throwing an error regarding SDK missing AdServices import as mentioned here in another issue: https://github.com/BranchMetrics/capacitor-branch-deep-links/issues/33. 

Branch please look into this plugin and update properly!

![Screen Shot 2021-09-24 at 5 09 39 pm](https://user-images.githubusercontent.com/70495867/134633246-efe9d26e-9db5-4495-b782-3f3616f75b0b.png)

**Comment by selected-pixel-jameson** [comment]
Well let's give them a break. This issue has only been open for 6 months. 😂

**Comment by Sampath-Lokuge** [comment]
Is this working with Capacitor 3 now? I can still see the Capacitor 2 doc here: https://help.branch.io/developers-hub/docs/capacitor

**Comment by selected-pixel-jameson** [comment]
@samitsawant Welcome to the party. No this repo will not compile successfully in iOS. See above comments. If you absolutely need to get this working you can use @paulstelzer's repo https://www.npmjs.com/package/@innomobile/capacitor-branch-deep-links.

**Comment by Sampath-Lokuge** [comment]
@selected-pixel-jameson Ok, it is disappointing to see no proper update plan for a commercial product like Branch.io.

**Comment by ksteuer** [comment]
+1. Is that true? This plugin has been outdated for 6 months after the release of Capacitor 3?

**Comment by Sampath-Lokuge** [comment]
@ksteuer You can use official plugin here and it is working perfectly fine: https://capacitorjs.com/docs/guides/deep-links

**Comment by selected-pixel-jameson** [comment]
@Sampath-Lokuge How do you use that with branch links? That demo is for Firebase Deep links.

**Comment by Sampath-Lokuge** [comment]
@selected-pixel-jameson I do not use Branch due to no Capacitor support. Deeplinks does not depend on Firebase. It is a generic solution.

**Comment by selected-pixel-jameson** [comment]
@Sampath-Lokuge Ah, ok. So it's an alternative approach.

**Comment by Sampath-Lokuge** [comment]
@selected-pixel-jameson Yes

**Comment by ksteuer** [comment]
@Sampath-Lokuge thanks for the suggestion. I'm going to check how it works in my case.

**Comment by Sampath-Lokuge** [comment]
@ksteuer Sure!

**Comment by michalsisak** [comment]
There is a new PR merged in the repo where Capacitor 3 seems to be supported: https://github.com/BranchMetrics/capacitor-branch-deep-links/pull/51.
Can anyone confirm?

**Comment by KirstenStake** [comment]
Can confirm. Upgraded plugin and seems to be working well for now. They also updated the CHANGELOG so see there for further info.
Thanks all! This one was a long time coming.
