### ISSUE TITLE
Android: BranchDeepLinks does not have web implementation

### ISSUE THREAD

**Issue by atishabhang** [BranchMetrics/capacitor-branch-deep-links#36]
I'm getting `BranchDeepLinks does not have web implementation` when I built a release `.apk`  from android studio.
But when I just hit run it works perfectly. 
Any idea why this is happening with the release builds only.?

```
Ionic:

   Ionic CLI                     : 6.12.3 (/home/atish/.nvm/versions/node/v14.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.5
   @angular-devkit/build-angular : 0.1102.10
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 11.2.10
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.6

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.3.0) : 1.2.2

System:

   NodeJS : v14.13.0 (/home/atish/.nvm/versions/node/v14.13.0/bin/node)
   npm    : 6.14.8
   OS     : Linux 5.8

```

**Comment by Trallo** [comment]
Does it have a web implementation? I am trying to use it in browser and getting that the BranchDeepLinks plugin is unavailable.
Using the following version "capacitor-branch-deep-links": "^4.2.0" .. Using capacitor 3 in the project..

**Comment by arianshirepublik** [comment]
Hi  When I used  "capacitor-branch-deep-links": "5.0.0",
It is sitll show errors:
<img width="829" alt="image" src="https://github.com/BranchMetrics/capacitor-branch-deep-links/assets/133647949/5766c061-8354-4d78-ae2a-ea1dc484c0e2">

**Comment by gdeluna-branch** [comment]
We currently don't support a capacitor web implementation.
