### ISSUE TITLE
Doc has not been updated to the Capacitor 3 yet

### ISSUE THREAD

**Issue by Sampath-Lokuge** [BranchMetrics/capacitor-branch-deep-links#54]
Hi,

It seems still to have the old doc here no?  https://help.branch.io/developers-hub/docs/capacitor

i.e. it says `Updated 4 months ago`?

So will we have an updated doc soon? Thanks!

**Comment by jf-branch** [comment]
Hi @Sampath-Lokuge, 

We did release support for this https://github.com/BranchMetrics/capacitor-branch-deep-links/releases/tag/v4.0.0. We will update our docs shortly to reference this.

**Comment by Sampath-Lokuge** [comment]
Hi @jf-branch 

Yes, this is super important to have the doc fully updated with all the latest changes hence we need to do a lot of native platform changes and etc. I hope you'll do that soon. Thanks a lot for the quick feedback.

**Comment by jf-branch** [comment]
Hi @Sampath-Lokuge, our docs have been updated: https://help.branch.io/developers-hub/docs/capacitor

**Comment by Sampath-Lokuge** [comment]
Hi @jf-branch 

Ok sure. This is great news. I'll inform my client too. Thanks a lot!
