### ISSUE TITLE
Capacitor 4 support

### ISSUE THREAD

**Issue by Sampath-Lokuge** [BranchMetrics/capacitor-branch-deep-links#60]
Hi,

Do you have any plan to support the latest Capacitor 4 with Branchio? Thanks!

`Announcing Capacitor 4.0`: https://ionicframework.com/blog/announcing-capacitor-4-0/

**Comment by psnfrench** [comment]
This is becoming critical as new Apps for Google play require targetSdkVersion 31, which can only be done using Capacitor 4. I.e. I don't think there is a way to use this plugin with new apps at the moment?

**Comment by Nathan187** [comment]
It would be nice to know this as well.  We are expecting to upgrade to capacitor 4 as well.

**Comment by jf-branch** [comment]
We have created an internal ticket and will look into this next sprint on Monday 8/22

**Comment by Sampath-Lokuge** [comment]
Nice. Thanks!

**Comment by popisdead** [comment]
keep us posted on the ETA

**Comment by gdeluna-branch** [comment]
This is in development, should be released next week.

**Comment by gdeluna-branch** [comment]
Released as of 5.0.0 https://www.npmjs.com/package/capacitor-branch-deep-links/v/5.0.0

**Comment by Sampath-Lokuge** [comment]
Great. Thanks!
