### ISSUE TITLE
'scanInt32(representation:)' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by yucehasan** [BranchMetrics/capacitor-branch-deep-links#62]
'scanInt32(representation:)' is only available in iOS 13.0 or newer'

Can you add check and fallback method here?

![Screen Shot 2022-08-19 at 11 16 37](https://user-images.githubusercontent.com/56137080/185575658-ed8b12b7-2d73-43bb-803c-efa77772da64.png)

**Comment by ggaabe** [comment]
For context, we get this error in `Development Pods -> CapacitorBranchDeepLinks -> Plugin.swift` even when our Podfile target and XCode Deployment target are both set to iOS 14.0.

**Comment by echo-branch** [comment]
Thanks for the bug report. I've made a ticket to address this soon.

**Comment by mileszim** [comment]
@echo-branch my dudes this release is unusable as it stands, can this be prioritized?

**Comment by gdeluna-branch** [comment]
As of https://github.com/BranchMetrics/capacitor-branch-deep-links/releases/tag/v5.0.0
https://www.npmjs.com/package/capacitor-branch-deep-links/v/5.0.0

We had to update to capacitor 4 and bump ios platform to 13. Please see official migration docs https://capacitorjs.com/docs/updating/4-0

**Comment by mileszim** [comment]
thank you @echo-branch!
