### ISSUE TITLE
Make compatible with Capacitor 5

### ISSUE THREAD

**Issue by Paso** [BranchMetrics/capacitor-branch-deep-links#97]
### Describe the feature

A Capacitor 5 project with this plugin won't build on android because of the package namespace/id being moved from AndroidManifest.xml to build.gradle. See https://capacitorjs.com/docs/next/updating/plugins/5-0

**Comment by Paso** [comment]
Capacitor 5.0.0 has been released now.

**Comment by 40818419** [comment]
any progress, guys?

**Comment by Sampath-Lokuge** [comment]
Any feedback here, please? We cannot use Branch with our app hence it crashes due to the above issue. i.e. not working on Android 13+

**Comment by gdeluna-branch** [comment]
Have a beta package here https://www.npmjs.com/package/capacitor-branch-deep-links/v/6.0.0-beta.0

Please test it out, we expect to release it next week.

**Comment by Sampath-Lokuge** [comment]
This is excellent news. Thanks!

**Comment by gdeluna-branch** [comment]
Published https://www.npmjs.com/package/capacitor-branch-deep-links/v/6.0.0
https://github.com/BranchMetrics/capacitor-branch-deep-links/releases/tag/v6.0.0
